settings:
  silver_path: "data/silver_delta/gupy"
  gold_output_path: "data/gold_delta"

  # Definição das tabelas que serão geradas na Gold
  tables:
    # 1. Tabela Principal de Vagas (Analítica)
    dim_vagas:
      enabled: true
      partition_by: ["ano_publicacao", "mes_publicacao"]

    # 2. Monitor de Skills (Ranking de tecnologias)
    agg_skills_monitor:
      enabled: true
      partition_by: ["data_referencia"] # Particiona pelo dia que rodou o relatório

    # 3. Tendências de Mercado (Séries Temporais)
    agg_market_trends:
      enabled: true
      partition_by: ["ano", "mes"]